### ISSUE TITLE
[Feature Request] Support for GGUF models (llama.cpp compatible)

### ISSUE THREAD

**Issue by syddharth** [neuml/txtchat#12]
These run on both GPU and CPU. A lot of OSS community uses them I guess, and the models are quite light on VRAM.

**Comment by davidmezzetti** [comment]
Thank you for submitting. 

If you're using txtai 6.2+ you can do the following.

```yaml
# Embeddings index
writable: false
cloud:
  provider: huggingface-hub
  container: neuml/txtai-wikipedia

# llama.cpp pipeline
llama_cpp.Llama:
    model_path: path to GGUF file

# Extractor pipeline
extractor:
  path: llama_cpp.Llama
  output: reference

txtchat.pipeline.wikisearch.Wikisearch:
  # Add application reference
  application:

workflow:
  wikisearch:
    tasks:
    - action: txtchat.pipeline.wikisearch.Wikisearch
```

You just need to make sure you also have https://github.com/abetlen/llama-cpp-python installed.
